const categories = [
  'Water', 'Hiking', 'Caves', 'Fishing', 'Scenic', 'Wildlife', 'Cycling', 'Camping', 'Family', 'History'
];

// Curated destination inventory for the Arkansas + Missouri Ozarks.
// These are places travelers can actually visit; partner/affiliate status is never implied.
const adventures = [
  ['buffalo-national-river','Buffalo National River','Arkansas Ozarks','Water','Float, paddle, fish, hike and camp along America\'s first national river.','https://www.nps.gov/buff/'],
  ['lost-valley-state-park','Lost Valley State Park','Ponca, AR','Hiking','Waterfalls, caves and bluff country on one of the Ozarks\' classic hikes.','https://www.arkansasstateparks.com/parks/lost-valley-state-park'],
  ['hemmed-in-hollow','Hemmed-In Hollow Falls','Buffalo River, AR','Hiking','A dramatic 200-foot waterfall tucked below the Buffalo River bluffs.','https://www.nps.gov/buff/planyourvisit/hemmed-in-hollow.htm'],
  ['whitaker-point','Whitaker Point / Hawksbill Crag','Washington County, AR','Scenic','The iconic cliff-edge overlook that defines an Ozarks road-trip photo.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43424'],
  ['sams-throne','Sam\'s Throne','Newton County, AR','Scenic','Massive sandstone bluffs, sweeping views and a legendary climbing area.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43425'],
  ['glory-hole-falls','Glory Hole Falls','Ozone, AR','Hiking','A waterfall pouring through a cave-like opening in the sandstone.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43428'],
  ['pedestal-rocks','Pedestal Rocks Scenic Area','Hector, AR','Hiking','Natural stone towers and overlooks along a short but unforgettable trail.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43431'],
  ['alum-cove-natural-bridge','Alum Cove Natural Bridge','Deer, AR','Hiking','A huge natural bridge, bluff shelters and forest trails in the Boston Mountains.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43422'],
  ['blanchard-springs-caverns','Blanchard Springs Caverns','Fifty-Six, AR','Caves','Go underground through one of the Ozarks\' most spectacular living cave systems.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43258'],
  ['devils-den-state-park','Devil\'s Den State Park','West Fork, AR','Camping','CCC-built Ozark scenery with caves, lake trails, camping and family adventures.','https://www.arkansasstateparks.com/parks/devils-den-state-park'],
  ['lake-fort-smith-state-park','Lake Fort Smith State Park','Mountainburg, AR','Water','Lake days, hiking and access to the Ozark Highlands Trail.','https://www.arkansasstateparks.com/parks/lake-fort-smith-state-park'],
  ['white-rock-mountain','White Rock Mountain','Ozark National Forest, AR','Scenic','High-elevation bluffs with big western Ozark sunsets and forest roads.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43448'],
  ['ozark-highlands-trail','Ozark Highlands Trail','Arkansas Ozarks','Hiking','A long-distance trail linking some of the wildest terrain in the state.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43418'],
  ['ozark-folk-center','Ozark Folk Center State Park','Mountain View, AR','History','Traditional Ozark crafts, music and mountain culture brought to life.','https://www.ozarkfolkcenter.com/'],
  ['mammoth-spring-state-park','Mammoth Spring State Park','Mammoth Spring, AR','Water','A huge natural spring feeding a beautiful mill pond and river.','https://www.arkansasstateparks.com/parks/mammoth-spring-state-park'],
  ['beaver-lake','Beaver Lake','Eureka Springs, AR','Water','Clear water, coves, cliffs, boating, fishing and miles of shoreline.','https://www.swl.usace.army.mil/Missions/Water-Management/Recreation/Beaver-Lake/'],
  ['lake-leatherwood','Lake Leatherwood City Park','Eureka Springs, AR','Water','A 1,600-acre Ozark playground for paddling, hiking, camping and cycling.','https://www.eurekasprings.com/lake-leatherwood-city-park/'],
  ['kings-river','Kings River','Eureka Springs region, AR','Water','A clear Ozark river known for paddling, fishing, wildlife and quiet gravel bars.','https://www.arkansas.com/things-to-do/outdoor-recreation/kings-river'],
  ['white-river-ozarks','White River Ozarks','North Central Arkansas','Fishing','Cold water, trout and scenic river valleys make this a legendary fishing corridor.','https://www.agfc.com/fishing/'],
  ['norfork-lake','Norfork Lake','Mountain Home, AR','Water','A sprawling clear-water reservoir with coves, cliffs, boating and fishing.','https://www.swl.usace.army.mil/Missions/Water-Management/Recreation/Norfork-Lake/'],
  ['bull-shoals-lake','Bull Shoals Lake','Bull Shoals, AR','Water','Ozark islands, clear coves, fishing and endless shoreline to explore.','https://www.swl.usace.army.mil/Missions/Water-Management/Recreation/Bull-Shoals-Lake/'],
  ['greers-ferry-lake','Greers Ferry Lake','Heber Springs, AR','Water','Clear mountain water, bluffs and huge open-water views.','https://www.swl.usace.army.mil/Missions/Water-Management/Recreation/Greers-Ferry-Lake/'],
  ['ozark-mountain-bike-trails','Ozark Mountain Bike Trails','Northwest Arkansas','Cycling','A dense network of purpose-built trails from beginner loops to technical rock.','https://www.oztrails.com/'],
  ['slaughter-pen-mountain-bike-park','Slaughter Pen Mountain Bike Park','Bentonville, AR','Cycling','One of the country\'s best-known free urban mountain-bike trail systems.','https://www.bentonvillear.com/'],
  ['coler-mountain-bike-preserve','Coler Mountain Bike Preserve','Bentonville, AR','Cycling','Wooded singletrack, bridges and the famous downhill hub near Bentonville.','https://www.oztrails.com/'],
  ['hobbs-state-park','Hobbs State Park-Conservation Area','Rogers, AR','Cycling','Arkansas\' largest state park delivers lake views, hiking and cycling.','https://www.arkansasstateparks.com/parks/hobbs-state-park-conservation-area'],
  ['devils-tea-table','Devil\'s Tea Table','Ozark National Forest, AR','Hiking','A bluff-top hike to a natural rock table overlooking the mountains.','https://www.fs.usda.gov/osfnf'],
  ['boxley-valley','Boxley Valley','Ponca, AR','Wildlife','Open pasture, dramatic bluffs and one of the best elk-viewing areas in Arkansas.','https://www.arkansas.com/places-to-go/cities-and-towns/ponca'],
  ['elk-viewing-ponca','Ponca Elk Viewing Area','Ponca, AR','Wildlife','Watch Arkansas elk at dawn and dusk in the Buffalo River valley.','https://www.agfc.com/hunting/elk/'],
  ['paddlers-park','Buffalo River Paddling Corridor','Ponca to Buffalo Point, AR','Water','Plan a multi-day float through towering bluffs, gravel bars and wilderness.','https://www.nps.gov/buff/planyourvisit/canoeing-kayaking.htm'],
  ['buffalo-point','Buffalo Point','Yellville, AR','Camping','A classic Buffalo River basecamp with river access, trails and big bluff scenery.','https://www.nps.gov/buff/planyourvisit/buffalo-point.htm'],
  ['steel-creek','Steel Creek Campground','Ponca, AR','Camping','Camp beneath towering bluffs where the Buffalo River turns spectacular.','https://www.nps.gov/buff/planyourvisit/steel-creek-campground.htm'],
  ['kyles-landing','Kyle\'s Landing','Buffalo National River, AR','Camping','A quieter Buffalo River launch and camping area surrounded by rugged country.','https://www.nps.gov/buff/'],
  ['ponca-low-water','Ponca Low-Water Bridge','Ponca, AR','Scenic','A signature Buffalo River crossing and gateway to some of the region\'s best trails.','https://www.nps.gov/buff/'],
  ['hurricane-river-cave','Hurricane River Cave','Cave City, AR','Caves','Explore a cave system with guided underground tours in the Ozark foothills.','https://www.hurricanerivercave.com/'],
  ['mystic-caverns','Mystic Caverns','Jasper, AR','Caves','A classic Ozarks cave attraction with dramatic formations and local legends.','https://www.mysticcaverns.com/'],
  ['cosmic-cavern','Cosmic Cavern','Berryville, AR','Caves','A privately operated cave with unusual formations and underground lakes.','https://www.cosmiccavern.com/'],
  ['war-eagle-cavern','War Eagle Cavern','Rogers, AR','Caves','A family-friendly cave and riverfront adventure near Beaver Lake.','https://wareaglecavern.com/'],
  ['thorncrown-chapel','Thorncrown Chapel','Eureka Springs, AR','Scenic','A glass-and-timber architectural icon nestled in the Ozark woods.','https://thorncrown.com/'],
  ['christ-of-the-ozarks','Christ of the Ozarks','Eureka Springs, AR','History','The famous 65-foot statue overlooking Eureka Springs and the Great Passion Play grounds.','https://www.greatpassionplay.org/'],
  ['great-passion-play','The Great Passion Play','Eureka Springs, AR','History','A massive outdoor production and Ozark attraction with 2026 performances.','https://www.greatpassionplay.org/'],
  ['eureka-springs-adventure-park','Eureka Springs Adventure Park','Eureka Springs, AR','Family','Aerial ropes, ziplines and forest challenges for an all-day adrenaline hit.','https://www.eurekaspringsadventurepark.com/'],
  ['eureka-springs-zipline','Eureka Springs Zipline','Eureka Springs, AR','Family','Zip through the forest canopy on a guided Ozark aerial adventure.','https://www.eurekaspringszipline.com/'],
  ['eureka-springs','Historic Eureka Springs','Eureka Springs, AR','History','Wander steep streets, springs, galleries and Victorian architecture in the hills.','https://www.visiteurekasprings.com/'],
  ['turpentine-creek-wildlife-refuge','Turpentine Creek Wildlife Refuge','Eureka Springs, AR','Wildlife','Meet rescued big cats and learn about wildlife rescue on a sprawling sanctuary.','https://www.turpentinecreek.org/'],
  ['blue-spring-heritage-center','Blue Spring Heritage Center','Eureka Springs, AR','History','A spring-fed historic site with gardens, trails and Cherokee history.','https://www.bluespringheritage.com/'],
  ['trigger-gap','Trigger Gap','Eureka Springs region, AR','Scenic','A mountain road and viewpoint with a storied history and sweeping Ozark terrain.','https://www.arkansas.com/'],
  ['pig-trail-scenic-byway','Pig Trail Scenic Byway','Ozark National Forest, AR','Scenic','Twisting pavement through deep forest, ridges and classic Ozark scenery.','https://www.arkansas.com/'],
  ['pig-trail-falls','Pig Trail Falls','Ozark National Forest, AR','Hiking','A roadside waterfall stop along one of the Ozarks\' most famous drives.','https://www.fs.usda.gov/osfnf'],
  ['mount-magazine-road','Boston Mountain Scenic Drive','Boston Mountains, AR','Scenic','Ride the ridges and valleys on a winding backroads tour of the Boston Mountains.','https://www.arkansas.com/'],
  ['mount-sequoyah','Mount Sequoyah','Eureka Springs, AR','Scenic','High above town with broad views across the forested hills.','https://www.eurekasprings.com/'],
  ['devils-den-lake-trail','Devil\'s Den Lake Trail','West Fork, AR','Hiking','A relaxed loop around the CCC-era lake with rock outcrops and forest shade.','https://www.arkansasstateparks.com/parks/devils-den-state-park'],
  ['yellow-rock-trail','Yellow Rock Trail','Devil\'s Den, AR','Hiking','Climb to a sandstone overlook with one of the park\'s best sunset views.','https://www.arkansasstateparks.com/parks/devils-den-state-park'],
  ['old-mill-trail','Old Mill Trail','Devil\'s Den, AR','History','Explore the historic structures and creek corridor inside Devil\'s Den.','https://www.arkansasstateparks.com/parks/devils-den-state-park'],
  ['buffalo-river-trail','Buffalo River Trail','Buffalo National River, AR','Hiking','Long-distance river-country hiking with bluffs, overlooks and remote camps.','https://www.nps.gov/buff/planyourvisit/hiking.htm'],
  ['lost-valley-trail','Lost Valley Trail','Ponca, AR','Hiking','A short, rewarding trail to Eden Falls and the Cob Cave area.','https://www.arkansasstateparks.com/parks/lost-valley-state-park'],
  ['eden-falls','Eden Falls','Ponca, AR','Hiking','A beautiful seasonal waterfall tucked into the Lost Valley canyon.','https://www.arkansasstateparks.com/parks/lost-valley-state-park'],
  ['goat-trail','Goat Trail','Buffalo National River, AR','Hiking','A cliff-hugging route with famous views of the Buffalo River below.','https://www.nps.gov/buff/planyourvisit/hiking.htm'],
  ['whitaker-creek','Whitaker Creek Campground','Buffalo National River, AR','Camping','A riverside base for hikers chasing Hawksbill Crag and nearby waterfalls.','https://www.nps.gov/buff/'],
  ['horseshoe-canyon-ranch','Horseshoe Canyon Ranch','Jasper, AR','Family','Climbing, rappelling and outdoor challenges on a working Ozark ranch.','https://horseshoecanyonranch.com/'],
  ['climbing-at-sams-throne','Sam\'s Throne Climbing','Ozark National Forest, AR','Hiking','Classic sandstone climbing above the Big Creek valley.','https://www.fs.usda.gov/osfnf'],
  ['buffalo-outdoor-center','Buffalo Outdoor Center','Ponca, AR','Water','A full-service Buffalo River outfitter for paddling, shuttles, lodging and trail adventures.','https://www.buffaloriver.com/'],
  ['rio-buffalo-outfitter','Rio Buffalo Outfitter','St. Joe, AR','Water','Canoe, kayak and raft rentals, shuttles and lodging for Buffalo River trips.','https://www.riobuffalo.com/'],
  ['kings-river-outfitters','Kings River Outfitters','Eureka Springs region, AR','Water','Canoe, kayak, shuttle and guided river adventures on the Kings River.','https://kingsriveroutfitters.com/'],
  ['gottagobuffalo','Gotta Go Buffalo','Buffalo River region, AR','Camping','Riverfront and treehouse-style stays that put the Buffalo adventure at your doorstep.','https://www.gottagobuffalo.com/'],
  ['float-eureka','Float Eureka','Eureka Springs, AR','Water','A relaxed way to get on the water and explore the Eureka Springs area.','https://www.floateureka.com/'],
  ['missouri-ozarks','Missouri Ozarks Adventure Country','Missouri Ozarks','Scenic','A huge playground of springs, rivers, caves, forests and state parks.','https://mostateparks.com/'],
  ['ha-ha-tonka-state-park','Ha Ha Tonka State Park','Camdenton, MO','Scenic','Castle ruins, karst bluffs, caves, springs and Lake of the Ozarks views.','https://mostateparks.com/park/ha-ha-tonka-state-park'],
  ['johnson-shut-ins','Johnson\'s Shut-Ins State Park','Middle Brook, MO','Water','Swim and scramble through volcanic rock chutes carved by the Black River.','https://mostateparks.com/park/johnsons-shut-ins-state-park'],
  ['elephant-rocks','Elephant Rocks State Park','Belleview, MO','Family','Giant granite boulders create a natural playground unlike anything else in the Ozarks.','https://mostateparks.com/park/elephant-rocks-state-park'],
  ['taum-sauk-mountain','Taum Sauk Mountain State Park','Middle Brook, MO','Hiking','Missouri\'s highest point, rugged ridges and the trail to Mina Sauk Falls.','https://mostateparks.com/park/taum-sauk-mountain-state-park'],
  ['mina-sauk-falls','Mina Sauk Falls','Taum Sauk Mountain, MO','Hiking','Missouri\'s highest waterfall on a rocky mountain trail.','https://mostateparks.com/park/taum-sauk-mountain-state-park'],
  ['ozark-trail-missouri','Ozark Trail','Missouri Ozarks','Hiking','A premier long-distance footpath crossing remote Ozark ridges, rivers and forests.','https://www.ozarktrail.com/'],
  ['current-river','Current River','Missouri Ozarks','Water','Spring-fed clear water for floating, fishing, paddling and camping.','https://www.nps.gov/ozar/'],
  ['jacks-fork-river','Jacks Fork River','Missouri Ozarks','Water','A wild, spring-fed river with towering bluffs and classic Missouri float trips.','https://www.nps.gov/ozar/'],
  ['eleven-point-river','Eleven Point National Scenic River','Missouri Ozarks','Water','Remote Ozark floating and hiking along a nationally protected spring-fed river.','https://www.nps.gov/ozar/planyourvisit/eleven-point.htm'],
  ['big-spring','Big Spring','Van Buren, MO','Scenic','One of the world\'s largest springs, erupting from the Ozark hills into the Current River.','https://mostateparks.com/park/big-spring-state-park'],
  ['alley-spring','Alley Spring','Eminence, MO','Scenic','Brilliant blue spring water and a historic red mill beside the Jacks Fork.','https://www.nps.gov/ozar/planyourvisit/alley-spring.htm'],
  ['blue-spring-missouri','Blue Spring','Eminence, MO','Scenic','A deep sapphire spring in a forested canyon along the Current River.','https://www.nps.gov/ozar/'],
  ['rocky-falls','Rocky Falls','Winona, MO','Water','A natural rock chute and swimming hole built into the Eleven Point country.','https://www.fs.usda.gov/mtnf'],
  ['peck-ranch-conservation-area','Peck Ranch Conservation Area','Winona, MO','Wildlife','Missouri wilderness with elk, deer, glades and miles of backcountry roads.','https://mdc.mo.gov/discover-nature/places/peck-ranch-conservation-area'],
  ['echo-bluff-state-park','Echo Bluff State Park','Eminence, MO','Camping','A modern basecamp for Current River country with dramatic limestone bluffs.','https://mostateparks.com/park/echo-bluff-state-park'],
  ['montauk-state-park','Montauk State Park','Salem, MO','Fishing','A legendary trout park built around a cold Ozark spring.','https://mostateparks.com/park/montauk-state-park'],
  ['bennett-spring-state-park','Bennett Spring State Park','Lebanon, MO','Fishing','A famous spring and trout stream with camping, hiking and floating nearby.','https://mostateparks.com/park/bennett-spring-state-park'],
  ['meramec-state-park','Meramec State Park','Sullivan, MO','Caves','River bluffs, trails and Fisher Cave on the Meramec River.','https://mostateparks.com/park/meramec-state-park'],
  ['fisher-cave','Fisher Cave','Meramec State Park, MO','Caves','A guided cave tour through chambers carved into the Meramec limestone.','https://mostateparks.com/park/meramec-state-park'],
  ['onondaga-cave','Onondaga Cave State Park','Leasburg, MO','Caves','Flowstone, stalactites and underground river scenery on guided cave tours.','https://mostateparks.com/park/onondaga-cave-state-park'],
  ['cave-spring','Cave Spring','Oregon County, MO','Scenic','A spring emerging from a cave along the Eleven Point River corridor.','https://www.fs.usda.gov/'],
  ['greer-spring','Greer Spring','Alton, MO','Hiking','A huge spring and one of the wildest scenic stops on the Ozark Trail.','https://www.fs.usda.gov/mtnf'],
  ['welch-spring','Welch Spring','Round Spring, MO','Scenic','A historic spring and former sanitarium ruins along the Current River.','https://www.nps.gov/ozar/'],
  ['devils-well','Devil\'s Well','Salem, MO','Caves','A spectacular karst sinkhole where underground water feeds the Current River system.','https://www.nps.gov/ozar/'],
  ['round-spring','Round Spring','Salem, MO','Camping','A scenic Current River spring with caves, camping and river access.','https://www.nps.gov/ozar/'],
  ['peck-ranch-elk','Missouri Ozarks Elk Country','Southern Missouri Ozarks','Wildlife','One of Missouri\'s best places to experience reintroduced elk in the wild.','https://mdc.mo.gov/discover-nature/places/peck-ranch-conservation-area'],
  ['table-rock-lake','Table Rock Lake','Branson, MO','Water','Clear mountain water, coves and marinas at the southern edge of the Ozarks.','https://www.swl.usace.army.mil/Missions/Water-Management/Recreation/Table-Rock-Lake/'],
  ['roaring-river-state-park','Roaring River State Park','Cassville, MO','Fishing','A deep blue spring, trout fishing, rugged hills and family camping.','https://mostateparks.com/park/roaring-river-state-park'],
  ['pere-marquette-state-park','Pere Marquette State Park','Grafton, IL','Scenic','Mississippi River bluffs at the eastern edge of the greater Ozark landscape.','https://dnr.illinois.gov/parks/park.pere-marquette.html'],
  ['devils-backbone-wilderness','Devil\'s Backbone Wilderness','Ozark County, MO','Hiking','Remote ridges, caves and hollows in Missouri\'s first wilderness area.','https://www.fs.usda.gov/mtnf'],
  ['glade-top-trail','Glade Top Trail','Mark Twain National Forest, MO','Scenic','A famous gravel scenic route crossing open glades and high Ozark ridges.','https://www.fs.usda.gov/recarea/mtnf/recarea/?recid=21748'],
  ['blue-hole-current-river','Blue Hole','Current River, MO','Water','A brilliant swimming and paddling stop along spring-fed Ozark water.','https://www.nps.gov/ozar/'],
  ['pulltite-campground','Pulltite Campground','Current River, MO','Camping','A forested riverside campground with direct access to the Current River.','https://www.nps.gov/ozar/'],
  ['akers-ferry','Akers Ferry','Current River, MO','History','A historic river crossing and launch point for exploring the Ozark backcountry.','https://www.nps.gov/ozar/'],
  ['wildcat-mountain','Wildcat Mountain','Arkansas Ozarks','Scenic','High ridge country with forest roads, rock outcrops and big valley views.','https://www.fs.usda.gov/osfnf'],
  ['hurricane-creek','Hurricane Creek Wilderness','Arkansas Ozarks','Hiking','Remote wilderness ridges and creek crossings for hikers who want solitude.','https://www.fs.usda.gov/osfnf'],
  ['upper-buffalo-wilderness','Upper Buffalo Wilderness','Arkansas Ozarks','Hiking','Wilderness trails, waterfalls and rugged country north of the Buffalo River.','https://www.fs.usda.gov/osfnf'],
  ['upper-buffalo-mountain-bike','Upper Buffalo Mountain Bike Trails','Ponca, AR','Cycling','Technical Ozark singletrack connecting forest, creek crossings and bluff country.','https://www.fs.usda.gov/osfnf'],
  ['lake-wedington','Lake Wedington Recreation Area','Fayetteville, AR','Water','A forested lake near Fayetteville for paddling, swimming, hiking and camping.','https://www.fs.usda.gov/recarea/osfnf/recarea/?recid=43438'],
  ['mulberry-river','Mulberry River','Arkansas Ozarks','Water','A favorite Ozark whitewater and floating river winding through forested mountains.','https://www.arkansas.com/things-to-do/outdoor-recreation/mulberry-river'],
  ['ozark-st-francis-forest','Ozark-St. Francis National Forests','Arkansas Ozarks','Camping','Millions of acres of forest, trails, lakes, rivers and remote campsites to explore.','https://www.fs.usda.gov/osfnf'],
  ['mark-twain-national-forest','Mark Twain National Forest','Missouri Ozarks','Camping','Millions of acres of public Ozark forest for hiking, hunting, paddling and camping.','https://www.fs.usda.gov/mtnf'],
  ['springfield-ozarks','Springfield Ozarks','Springfield, MO','Family','Use Springfield as a launchpad for caves, rivers, trails, food and road trips.','https://www.springfieldmo.org/'],
  ['branson-outdoors','Branson Ozarks Outdoors','Branson, MO','Family','Lakes, trails, zip lines and outdoor attractions surround the Branson hills.','https://www.explorebranson.com/'],
  ['bentonville-ozarks','Bentonville Ozarks Adventure Hub','Bentonville, AR','Cycling','World-class cycling, public art, trails and a walkable downtown basecamp.','https://www.visitbentonville.com/'],
  ['fayetteville-ozarks','Fayetteville Ozarks Adventure Hub','Fayetteville, AR','Family','A lively college-town base for trails, cycling, food and nearby mountain adventures.','https://www.experiencefayetteville.com/']
].map(([slug, name, region, category, description, url], index) => ({
  id: index + 1,
  slug, name, region, category, description, url,
  featured: index < 12,
  founding: true,
  status: 'unclaimed'
}));

function getAdventureDirectory({ category = 'all', region = 'all' } = {}) {
  return adventures.filter(a =>
    (category === 'all' || a.category === category) &&
    (region === 'all' || a.region.includes(region))
  );
}

module.exports = { adventures, categories, getAdventureDirectory };
